Algoritmo "comando PAUSAA"

Var
    i, primeiro, segundo: inteiro

Inicio

     escreval("Digite o primeiro: ")
     leia(primeiro)

     
     escreval("Digite o segundo: ")
     leia(segundo)

     escreval()

      para i de primeiro ate segundo faca
              escreval(i)
              escreval("Programa pausado! Click no Botão de Execulta(F9)")
              pausa
      fimpara


Fimalgoritmo