Algoritmo "PARA DE ATE FACA"

Var
   //VARIAVÉL CONTADORA
   contador: inteiro

Inicio

  //AQUI ELE VAI REPETIR 10 VEZ, PORDERIA SER MAIS, MENOS, MAIS COLOQUEI SO 10
  //VAI COMEÇA DO 1, AI 2, 3, 4... 10. E A VARIAVEL CONTADORA VAI RECEBER OS VALORES DE
  //1 ATE 10
   para contador de 1 ate 10 faca
   // PRIMEIRO 1
      //AI ELE ESVREVE 1
        escreva(contador, ",")
        //DEPOIS ELE RETOR PRO "PARA" contadora recebe 1 depoia 2, 3 e assim até o 10
   fimpara

Fimalgoritmo